name: My Workflow
on:
  push:
    

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '#NORUN') }}
    runs-on: ubuntu-latest
    steps:
    # checkout
    - name: Checkout
      uses: actions/checkout@v4

    # Scan with trivy
    - name: Scanning
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        severity: 'HIGH'
        output: 'trivy-results.txt'

    # Send slack noti
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.26.0
      with:
        channel_id: ${{ secrets.SLACK_CHANNEL_ID_T }}
        slack-message: "*Scan failed - Than Win Han*\nFailed trivy scan, see uploaded report"
      env: 
        SLACK_WEBHOOK_URL:  ${{ secrets.SLACK_WEBHOOK_URL_T }}

    # Upload file to Slack
    - uses: MeilCli/slack-upload-file@v4
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channel_id: ${{ secrets.SLACK_CHANNEL_ID_T }}
        file_path: 'trivy-results.txt'
        initial_comment: 'Scan report by Than Win Han'

