name: My Workflow
on:
  push:
    branches:
      - 'release/v*.*'
      - '!v*.*-beta'
      - '!release/v*.*.*'
      - '!feature-01'

jobs:
  success: 
    if: ${{ !contains(github.event.head_commit.message, '#NORUN') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Scanning
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          severity: 'CRITICAL'
          output: 'trivy-results.txt'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
       uses: docker/login-action@v3
       with: 
        username:
        password: 
      
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 




  fail:
    if: ${{ !contains(github.event.head_commit.message, '#NORUN') }}
    runs-on: ubuntu-latest
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Scan with trivy
      - name: Scanning
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          severity: 'HIGH'
          output: 'trivy-results.txt'

      # Send slack noti
      - name: Send GitHub Action trigger data to Slack workflow
        uses: rtCamp/action-slack-notify@v2
        env: 
          SLACK_COLOR: 'failure'
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID_T }}
          SLACK_TITLE: "Scan failed - Than Win Han"
          SLACK_MESSAGE:  |
            Failed trivy scan, see uploaded report

      # Upload file to Slack
      - uses: MeilCli/slack-upload-file@v4
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID_T }}
          file_path: 'trivy-results.txt'
          initial_comment: 'Scan report by Than Win Han'

