name: My Workflow
on:
  push:
    

jobs:
  test:
    
    runs-on: ubuntu-latest
    steps:
    # checkout
    - name: Checkout
      uses: actions/checkout@v4

    # Scan with trivy
    - name: Scanning
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'table'
        severity: 'LOW'
        output: 'trivy-results.txt'

    # Send slack noti
    - name: Send GitHub Action trigger data to Slack workflow
      uses: slackapi/slack-github-action@v1.26.0
      env: 
        SLACK_COLOR: '#FF0000'
        SLACK_TITLE:  'Scan failed - Than Win Han'
        SLACK_MESSAGE:  |
          Failed trivy scan, see uploaded report
        SLACK_WEBHOOK_URL:  ${{ secrets.SLACK_WEBHOOK_URL_T }}

    # Upload file to Slack
    - uses: MeilCli/slack-upload-file@v4
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channel_id: ${{ secrets.SLACK_CHANNEL_ID_T }}
        file_path: 'trivy-results.txt'
        initial_comment: 'Scan report by Than Win Han'

